### PR TITLE
Webms in gallery mode

### PR DESCRIPTION
**Pull request by mitchross**
Add WebM to gallery mode swipe. Checks for webm in url, if not webm, then use standard view for .gif

fixes https://github.com/Rukkaitto/mobichan/issues/25

### CODE REVIEW

**Comment by mitchross** [comment]
Looks like you might already have a branch for this. This is a simplistic approach. Take it or leave it, doesn't matter to me.

**Comment by Rukkaitto** [comment]
There's one issue : webms don't stop playing after being swiped to the side. Results in webms playing sound over each other.

**Comment by mitchross** [comment]
@Rukkaitto 
I see in dev tools multiple webm viewer pages are being created, thus explaining the issue you are seeing.
image


There's a few ways to solve this.

1. Create a swipe listener that pauses the video and potentially disposes the player itself. I know how to do this in java/android, gotta do some research for dart/flutter. 

2. Create a static webmviewer page, Flutter vlc supports a single player and swapping out the play URL, so you have 1 player, but change its URL its loading... this might be trickier with the gallery page mechanisms but should be doable.

**Comment by Rukkaitto** [comment]
You should take a look at feature/webm-swipe, in my last commit I came up with my solution, not sure if it's ideal though.

**Comment by mitchross** [comment]
@Rukkaitto I took a look at that branch, that's basically the same path I was thinking through. That will work, lets get that merged in and you can close this.

If you have more bugs log em.

**Comment by mitchross** [comment]
@Rukkaitto  did you mean to merge this?  I was referring to your current webM feature branch that should merge

**Comment by Rukkaitto** [comment]
> @Rukkaitto  did you mean to merge this?  I was referring to your current webM feature branch that should merge
> 

I misunderstood, but I'll fix the issue we were talking about.

**Comment by mitchross** [comment]
@Rukkaitto my discord thellamafarm#7609 if you want to chat thru this. I have a few more ideas.

**Pull request merged**
