### PR TITLE
Updates to packages

### PR DESCRIPTION
**Pull request by mitchross**
Mostly Package Updates and some dart 3 readiness.  Ran Dart Analyze / Fix.

### CODE REVIEW

**Comment by mitchross** [comment]
@Rukkaitto

**Comment by Rukkaitto** [comment]
Thanks for the PR,

`build_runner` is causing some issues:

```bash
Because build_runner 2.4.1 requires SDK version >=3.0.0-134.0.dev <4.0.0 and no versions of build_runner match >2.4.1 <3.0.0, build_runner ^2.4.1 is forbidden.
So, because mobichan depends on build_runner ^2.4.1, version solving failed.
```

**Comment by mitchross** [comment]
> Thanks for the PR,
> 
> `build_runner` is causing some issues:
> 
> ```shell
> Because build_runner 2.4.1 requires SDK version >=3.0.0-134.0.dev <4.0.0 and no versions of build_runner match >2.4.1 <3.0.0, build_runner ^2.4.1 is forbidden.
> So, because mobichan depends on build_runner ^2.4.1, version solving failed.
> ```

Building locally? do a flutter upgrade if you havent.

**Comment by mitchross** [comment]
@Rukkaitto  should be resolved now

**Comment by mitchross** [comment]
@Rukkaitto  I pushed more updates for dart 3, flutter v3. You just need to accept terms and the build failure should get fixed...

**Pull request merged**
