### PR TITLE
[DRAFT] Gallery view

### PR DESCRIPTION
**Pull request by mitchross**
Adds Gallery View for images in threads

Still needs some error handling logic. 
Need to modify for webM logic.
Themeing, etc

You either merge now tune it to your likings and I'll tweak webM later

Screen Shot 2021-07-07 at 9 51 13 PM
Screen Shot 2021-07-07 at 9 51 07 PM
Screen Shot 2021-07-07 at 9 51 02 PM

### CODE REVIEW

**Comment by Rukkaitto** [comment]
image
Most of the images 404 but I like it so far

**Comment by mitchross** [comment]
@Rukkaitto  I pushed up a fix. Im trying to figure out how to use non-thumbnail images. According to https://github.com/4chan/4chan-API/blob/master/pages/User_images_and_static_content.md you remove the "s" for non-thumnail as the 's' selects thumbnail.

if you pull down again you should see the gallery working as expected, just lower res images.

**Comment by mitchross** [comment]
Resolved conflicts

**Comment by Rukkaitto** [comment]
> @Rukkaitto I pushed up a fix. Im trying to figure out how to use non-thumbnail images. According to https://github.com/4chan/4chan-API/blob/master/pages/User_images_and_static_content.md you remove the "s" for non-thumnail as the 's' selects thumbnail.
> 
> if you pull down again you should see the gallery working as expected, just lower res images.

Non thumbnail images are used like this : https://i.4cdn.org/$board/${post.tim}.${post.ext}

**Comment by mitchross** [comment]
@Rukkaitto ill be out on vacation for a week so you can either merge and take care of the images urls or wait till I get back.

**Comment by Rukkaitto** [comment]
> @Rukkaitto ill be out on vacation for a week so you can either merge and take care of the images urls or wait till I get back. 

I'll take care of it when I have the time, thanks.

**Comment by Rukkaitto** [comment]
Merged in fc95eb8a14fc91568d275b9e23ce1412299520f9.

**Pull request closed without merging**
